source "https://rubygems.org"

gem "space_shoes", path: ".."

gem "ruby_wasm", "~> 2.5"
gem "js"
gem "lacci", "~>0.4.0", github: "scarpe-team/scarpe", glob: "lacci/*.gemspec"
gem "scarpe-components", "~>0.4.0"
